### ISSUE TITLE
Old County Data

### ISSUE THREAD

**Issue by nikAleksandr** [topojson/us-atlas#22]
County data reflects older maps and does not include several counties and equivalents, including the most recent addition "Petersburg, AK" with FIPS 02195

**Comment by bhrutledge** [comment]
Looks like [Makefile](https://github.com/mbostock/us-atlas/blob/bf502099b48e54116c88f277e6d800836ecbc210/Makefile#L66) refers to an older version of the county data.

A newer one lives at http://dds.cr.usgs.gov/pub/data/nationalatlas/countyp010g.shp_nt00934.tar.gz, found via the [Small-Scale Data Download](http://nationalmap.gov/small_scale/atlasftp.html?openChapters=chpbound#chpbound).

**Comment by mbostock** [comment]
I’ve started working on updates over in #23, but there’s quite a bit more work to do.

**Comment by mbostock** [comment]
As of 0.1, I’m using the latest 2015 edition of the Census Bureau’s [cartographic boundary files](http://www.census.gov/geo/maps-data/data/cbf/cbf_counties.html). Example here: http://bl.ocks.org/mbostock/4060606
