### ISSUE TITLE
Create zcta5 or zcta3 topojson?

### ISSUE THREAD

**Issue by dfrankow** [topojson/us-atlas#31]
Zipcodes are not geographic regions. Nevertheless, there are zipcode tabulation areas (ZCTAs) from the U.S. census. There are also several github projects to try to make those usable with geojson. For example, https://github.com/jgoodall/us-maps.

I also tried to cobble together some zcta5 topojson to display (actually I wanted zcta3). I ran into [an issue](https://github.com/mbostock/ndjson-cli/issues/35), as jgoodall did.

It would be nice to have ZCTA5 (or for me ZCTA3) topojson somewhere.

**Comment by mbostock** [comment]
I don’t have the bandwidth at the moment to make this us-atlas exhaustive, so I suggest if you want something besides counties or states, you go directly to the U.S. Census source data and modify the prepublish script as you see fit. Apologies!
