### ISSUE TITLE
Output json file displays features upside down in tools such as QGIS and Felt

### ISSUE THREAD

**Issue by jsolly** [topojson/us-atlas#44]
## Steps to reproduce.
1 - Go to the [README.md](https://github.com/topojson/us-atlas) and download the [counties-albers-10m.json](https://cdn.jsdelivr.net/npm/us-atlas@3/counties-albers-10m.json) file
2 - Open the file in Qgis or use Felt's online tool's 'upload anything' functionality.

![CleanShot 2024-06-18 at 08 29 52](https://github.com/topojson/us-atlas/assets/9572232/f492825a-52cb-4e14-8c68-1ae5349fd705)

Everything is upside down.

## Thoughts
I see in the [observable notebook](https://observablehq.com/@d3/u-s-map-canvas) that it is using D3 for rendering, and it seems to put everything correctly side up, but is there a way I can make this work in a desktop GIS tool like QGIS?

It seems that all that needs to be done is flip the features across the x-axis (latitude line), but I'm unsure how best to do this.

**Comment by mbostock** [comment]
Different tools make different assumptions about how to display protected coordinates. There are various tools for reprojecting or transforming projected coordinates if you want to invert the y-axis.

**Comment by jsolly** [comment]
I got it the correct way up by applying an affine transformation in Qgis with the y-axis scale factor set to `-1`. I didn't find a way to do it in GDAL within a terminal command 
![CleanShot 2024-06-18 at 13 11 08](https://github.com/topojson/us-atlas/assets/9572232/28421a43-c938-47bc-8035-b64351c541ad)
